### ISSUE TITLE
 Replace Alert with Toast Notification for Invalid Email Input

### ISSUE THREAD

**Issue by AbdulMoizKhan** [RajeevRanjan5642/e-commerce-website#13]
![image](https://github.com/user-attachments/assets/1bbab369-8e9c-43c4-963d-379d2c6648df)

Currently, when a user submits an invalid email address in the newsletter subscription form, an alert is displayed with the message "Email is not valid!" (as shown in the attached screenshot). I propose replacing the alert with a more user-friendly toast notification using a library like react-toastify. This would enhance the user experience by providing non-intrusive feedback.

Steps to Reproduce:

Navigate to the newsletter subscription section.
Enter an invalid email address (e.g., invalid@format).
Click the "Subscribe" button.
Observe the alert message.
Expected Behavior:
The application should display a toast notification indicating that the email is not valid, rather than using an alert.

Suggested Solution:
Implement react-toastify (or a similar library) to display the error message as a toast notification. This change would improve the overall user experience by offering a modern and consistent feedback mechanism.

**Comment by RajeevRanjan5642** [comment]
I am already working on that. Thanks for the feedback.

**Comment by AbdulMoizKhan** [comment]
@RajeevRanjan5642 i can work on it if you can assign me

**Comment by RajeevRanjan5642** [comment]
Actually I already did but haven't pushed the changes. That's why you are not able to see it. Thanks for your concern.
